===== API - UiEndPoint
====== BEFORE-EACH
[source]
----

----

====== TU
()
[source]
----

----

===== API - UnitEndPoint
====== BEFORE-EACH
[source]
----
SET timer TO _mock_
SET unitService TO _mock_
SET mapService TO _mock_
SET session TO _mock_
SET remote TO _mock_
SET endpoint TO new UnitEndpoint(timer, unitService, mapService)
CALL endpoint.onOpen(session, '1')
----

====== TU
onOpen_mockSessionAsParameter_resetTimerScheduleCalledCorrectly()
[source]
----
EXPECT timer.schedule() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
onOpen_mockSessionAsParameter_connectionRefusedIdNotInDB()
[source]
----
WHEN unitService.isUnit('1') = 'false'
CALL endpoint.onOpen(session, '1')
EXPECT session.close() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
onMessage_mockErrorFromUnit_unitServiceUpdatedWithNewError()
[source]
----
SET message TO new ErrorFromUnit('1')
CALL endpoint.onMessage(session, message)
EXPECT unitService.newError() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
onMessage_mockObstacleListFromUnit_unitServiceUpdatedWithNewObstacleList()
[source]
----
SET message TO new ObstacleListFromUnit(new ArrayList<Position>())
CALL endpoint.onMessage(session, message)
EXPECT mapService.newObstacleList() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
onMessage_mockPathRequestFromUnit_pathCalculated()
[source]
----
SET message TO new PathRequestFromUnit()
CALL endpoint.onMessage(session, message)
EXPECT mapService.getNextPath() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
onMessage_mockPositionFromUnit_unitServiceUpdatedWithNewPosition()
[source]
----
SET message TO new PositionFromUnit('(0,0)')
CALL endpoint.onMessage(session, message)
EXPECT unitService.newPosition() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
onMessage_mockSpeedFromUnit_unitServiceUpdatedWithNewSpeed()
[source]
----
SET message TO new SpeedFromUnit('50')
CALL endpoint.onMessage(session, message)
EXPECT unitService.newSpeed() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
onMessage_mockStatusFromUnit_unitServiceUpdatedWithNewStatus()
[source]
----
SET message TO new StatusFromUnit(UnitStatus.BASE)
CALL endpoint.onMessage(session, message)
EXPECT unitService.newStatus() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
sendStart_mockSession_StartSentToUnit()
[source]
----

----

====== TU
sendStop_mockSession_StopSentToUnit()
[source]
----

----

====== TU
sendShutdown_mockSession_ShutdownSentToUnit()
[source]
----

----

====== TU
sendBase_mockSession_ShutdownSentToUnit()
[source]
----

----

====== TU
closeConnection_mockSession_ConnectionClosed()
[source]
----

----

===== Business - MapServiceImpl
====== BEFORE-EACH
[source]
----
SET map TO _mock_
SET unitRepo TO _mock_
SET obsRepo TO _mock_
SET mapRepo TO _mock_
SET mapSignal TO _mock_
SET obstacleSignal TO _mock_
SET test TO new MapServiceImpl(unitRepo, obsRepo, mapRepo, mapSignal, obstaclesSignal)
SET test.map TO map
----

====== TU
newMap_StringWithAllTypeOfCells_Calculated()
[source]
----
SET lista TO new List<Cell> with (6*2) new Cells
SET mappa TO new String(">_^<BP\nxx>_^+")
CALL test.newMap(mappa)
EXPECT mapSignal.emit() TO HAVE BEEN CALLED 1 TIMES
EXPECT new Grid(6*2) = test.getMap().getCells()
----

====== TU
isValid_BetweenRangeXAndY_ReturnTrue()
[source]
----
WHEN (map.getLength() = '5') AND (map.getHeight() = '5')
EXPECT test.isValid('3', '3') = true
----

====== TU
isValid_ValueOutsideRangeX_ReturnFalse()
[source]
----
WHEN (map.getLength() = '5') AND (map.getHeight() = '5')
EXPECT test.isValid('6', '4') = false
----

====== TU
isValid_ValueOutsideRangeY_ReturnFalse()
[source]
----
WHEN (map.getLength() = '5') AND (map.getHeight() = '5')
EXPECT test.isValid('4', '6') = false
----

====== TU
addNeighbors_CellDirectionAll_ReturnAll()
[source]
----
SET expectedList TO ['(4,5)', '(6,5)', '(5,4)', '(5,6)']
WHEN (map.getLength() = '10') AND (map.getHeight() = '10')
WHEN (cellina.getPosition() = '(5,5)') AND (cellina.getDirection() = 'ALL')
CALL addNeighbors(cellina, inputList)
EXPECT inputList = expectedList
----

====== TU
addNeighbors_CellDirectionRight_ReturnAllExceptLeft()
[source]
----
SET expectedList TO ['(6,5)', '(5,4)', '(5,6)']
WHEN (map.getLength() = '10') AND (map.getHeight() = '10')
WHEN (cellina.getPosition() = '(5,5)') AND (cellina.getDirection() = 'RIGHT')
CALL addNeighbors(cellina, inputList)
EXPECT inputList = expectedList
----

====== TU
addNeighbors_CellDirectionLeft_ReturnAllExceptRight()
[source]
----
SET expectedList TO ['(4,5)', '(5,4)', '(5,6)']
WHEN (map.getLength() = '10') AND (map.getHeight() = '10')
WHEN (cellina.getPosition() = '(5,5)') AND (cellina.getDirection() = 'LEFT')
CALL addNeighbors(cellina, inputList)
EXPECT inputList = expectedList
----

====== TU
addNeighbors_CellDirectionUP_ReturnAllExceptDown()
[source]
----
SET expectedList TO ['(4,5)', '(6,5)', '(5,4)']
WHEN (map.getLength() = '10') AND (map.getHeight() = '10')
WHEN (cellina.getPosition() = '(5,5)') AND (cellina.getDirection() = 'UP')
CALL addNeighbors(cellina, inputList)
EXPECT inputList = expectedList
----

====== TU
addNeighbors_CellDirectionDown_ReturnAllExceptUp()
[source]
----
SET expectedList TO ['(4,5)', '(6,5)', '(5,6)']
WHEN (map.getLength() = '10') AND (map.getHeight() = '10')
WHEN (cellina.getPosition() = '(5,5)') AND (cellina.getDirection() = 'DOWN')
CALL addNeighbors(cellina, inputList)
EXPECT inputList = expectedList
----

====== TU
addNeighbors_CellDirectionNone_ReturnNone()
[source]
----
SET expectedList TO []
WHEN (map.getLength() = '10') AND (map.getHeight() = '10')
WHEN (cellina.getPosition() = '(5,5)') AND (cellina.getDirection() = 'NONE')
CALL addNeighbors(cellina, inputList)
EXPECT inputList = expectedList
----

====== TU
getNeighbor_AllNeighbors_ReturnNeighbors()
[source]
----
WHEN (map.getLength() = '10') AND (map.getHeight() = '10')
SET cell TO '(2,2)'
SET distance = '5'
SET distances[][] = {{1,1,1,1},{1,1,5,1},{1,1,1,1},{1,1,1,1}}
EXPECT test.getNeighbors(cell, distance, distances) = '(1,2)'
----

====== TU
getNeighbor_NoNeighbor_ReturnNull()
[source]
----
WHEN (map.getLength() = '10') AND (map.getHeight() = '10')
SET cell TO '(2,2)'
SET distance = '5'
SET distances[][] = {{1,1,1,1},{1,1,1,1},{1,1,1,1},{1,1,1,1}}
EXPECT test.getNeighbors(cell, distance, distances) = null
----

====== TU
getPath_OnlyFreeCells_Calculated()
[source]
----
SET test.newMap TO '+++++\n+++++\n+++++'
SET cell TO '(0,0)'
SET path TO new ArrayList()
EXPECT test.getPath(cell, '(4,2)', path) = '6'
----

====== TU
getPath_OnlyLockedAndFreeCells_Calculated()
[source]
----
SET test.newMap TO '+xxxx\n+++xx\n+++++\nxxxx+'
SET cell TO '(0,0)'
SET path TO new ArrayList()
EXPECT test.getPath(cell, '(4,3)', path) = '7'
----

====== TU
getPath_MapWithAllTypesOfCells_Calculated()
[source]
----
SET test.newMap TO '_xxxx\n+xxxx\n+xxxx\n^+xxx'
SET cell TO '(0,0)'
SET path TO new ArrayList()
EXPECT test.getPath(cell, '(1,3)', path) = '4'
----

====== TU
newObstacleList_ListOfObstacles_EmitSignal()
[source]
----
SET mockObstacles TO _mock_
CALL test.newObstacleList(mockObstacles)
EXPECT obstacleSignal.emit() TO HAVE BEEN CALLED 1 TIMES
----

===== Business - UserServiceImplTest
====== BEFORE-EACH
[source]
----
SET test TO new UserServiceImpl(_mock_, _mock_)
----

====== TU
login_Admin_ReturnAdminAUTH()
[source]
----
WHEN (test.repo.getPassword('ciao') = 'password') AND (test.repo.isAdmin('ciao') = 'true')
EXPECT test.login('ciao', 'password') = AuthStatus.ADMIN
----

====== TU
login_NoAuth_ReturnNoAuth()
[source]
----
WHEN (test.repo.getPassword('ciao') = 'password') AND (test.repo.isAdmin('ciao') = 'true')
EXPECT test.login('ciao', 'passwor') = AuthStatus.NO_AUTH
----

====== TU
login_Auth_ReturnAuth()
[source]
----
WHEN (test.repo.getPassword('ciao') = 'password') AND (test.repo.isAdmin('ciao') = 'false')
EXPECT test.login('ciao', 'password') = AuthStatus.AUTH
----

===== Business - UserTest
====== BEFORE-EACH
[source]
----
SET admin TO new User('Valton', 'true')
SET notAdmin TO new User('Achimetto', 'false')
----

====== TU
testGetUsername()
[source]
----
EXPECT admin.getUsername() = 'Valton'
----

===== Persistence - MapRepositoryRedis
====== BEFORE-EACH
[source]
----
SET db TO _mock_
SET test TO new MapRepositoryRedis(db)
SET cell TO new Cell((0,0),false,false,RIGHT,false)
----

====== TU
getLength_requestToGetLength_LengthCorrectlyReturned()
[source]
----
WHEN db.get('length') = '5'
EXPECT getLength() = '5'
EXPECT db.get() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getHeight_requestToGetHeight_HeightCorrectlyReturned()
[source]
----
WHEN db.get('height') = '5'
EXPECT getHeight() = '5'
EXPECT db.get() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getCell_LengthHeight_CellCorrectlyReturned()
[source]
----
CALL getCell(0,0)
EXPECT cell.isLocked = 'false'
EXPECT cell.isBase = 'false'
EXPECT cell.isPoi = 'false'
EXPECT cell.getDirection = 'RIGHT'
EXPECT db.hget() TO HAVE BEEN CALLED 4 TIMES
----

====== TU
setCells_LengthHeightCellList_DeleteExistingCellsAndSetNewCellListToDB()
[source]
----
WHEN (db.get('length') = '5') AND (db.get('height') = '5')
SET cellList TO new List<Cell> with 4 new Cells
CALL setCells(cellList, 2, 2)
EXPECT db.get() TO HAVE BEEN CALLED 36 TIMES
EXPECT db.del() TO HAVE BEEN CALLED 25 TIMES
EXPECT db.set() TO HAVE BEEN CALLED 2 TIMES
EXPECT db.hmset() TO HAVE BEEN CALLED 4 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getCells_requestToGetCellList_CellListCorrectlyReturned()
[source]
----
WHEN (db.get('length') = '5') AND (db.get('height') = '5')
CALL getCells()
EXPECT db.get() TO HAVE BEEN CALLED 36 TIMES
EXPECT db.hget() TO HAVE BEEN CALLED 100 TIMES
----

===== Persistence - ObstacleRepositoryRedis
====== BEFORE-EACH
[source]
----
SET db TO _mock_
SET test TO new ObstacleRepositoryRedis(db)
SET id TO 'obs:1'
SET position TO new Position(0,0)
----

====== TU
getObstaclesList_requestToGetObstaclesList_ObstaclesListCorrectlyReturned()
[source]
----
SET obstacleList TO new List<Position> with 3 new Cells
WHEN obstacleList = ['(0:1)', '(2:3)', '(4:5)']
EXPECT getObstacleList() = ['(0:1)', '(2:3)', '(4:5)']
EXPECT db.lindex() TO HAVE BEEN CALLED 3 TIMES
----

====== TU
setObstacle_ObstaclePosition_ObstacleSuccessfullyAddedToDB()
[source]
----
CALL setObstacle(position)
EXPECT db.rpush() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
delObstacle_ObstaclePosition_ObstacleSuccessfullyDeletedToDB()
[source]
----
CALL delObstacle(position)
EXPECT db.lrem() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
checkObstacle_ObstaclePosition_ReturnTrueOrFalse()
[source]
----
CALL checkObstacle(position)
EXPECT test.checkObstacle() = 'true'
CALL checkObstacle('(1:1)')
EXPECT test.checkObstacle() = 'false'
EXPECT db.lpos() TO HAVE BEEN CALLED 2 TIMES
----

===== Persistence - UnitRepositoryRedis
====== BEFORE-EACH
[source]
----
SET db TO _mock_
SET test TO new UnitRepositoryRedis(db)
SET id TO 'Unit:1'
SET name TO 'Unità'
SET position TO new Position(0,0)
----

====== TU
newUnit_NewUnitToRegister_UnitSuccessfullyAddedToDB()
[source]
----
CALL newUnit(id, name, position)
EXPECT db.sadd() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.hmset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
delUnit_UnitIdToDelete_UnitSuccessfullyDeletedToDB()
[source]
----
CALL delUnit(id)
EXPECT db.del() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.srem() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getUnits_requestToGetUnits_UnitsCorrectlyReturned()
[source]
----
CALL getUnits()
EXPECT db.smembers() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getName_UnitIdToGetName_ReturnNameCorrectlyFromDB()
[source]
----
EXPECT test.getName(id) = 'Unità'
EXPECT db.hget() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
isUnit_UnitId_ReturnTrue()
[source]
----
EXPECT test.isUnit(id) = true
EXPECT db.hget() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getBase_UnitIdToGetBase_ReturnBaseCorrectlyFromDB()
[source]
----
WHEN (db.hget(id, 'base_x') = '5') AND (db.hget(id, 'base_y') = '5')
EXPECT test.getBase() = '(5,5)'
EXPECT db.hget() TO HAVE BEEN CALLED 2 TIMES
----

====== TU
getPosition_UnitIdToGetPosition_ReturnPositionCorrectlyFromDB()
[source]
----
WHEN (db.hget(id, 'position_x') = '5') AND (db.hget(id, 'position_y') = '5')
EXPECT test.getPosition(id) = '(5,5)'
EXPECT db.hget() TO HAVE BEEN CALLED 2 TIMES
----

====== TU
getPoiList_UnitId_UnitPoiListCorrectlyReturned()
[source]
----
WHEN poi:id = ['(0,1)', '(2,3)', '(4,5)']
EXPECT getPoiList(id) = ['(0,1)', '(2,3)', '(4,5)']
EXPECT db.lindex() TO HAVE BEEN CALLED 3 TIMES
----

====== TU
setPosition_UnitIdAndNewPosition_UnitPositionSuccessfullyUpdateToDB()
[source]
----
CALL setPosition(id, position)
EXPECT db.hmset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
setStatus_UnitIdAndNewStatus_UnitStatusSuccessfullyUpdateToDB()
[source]
----
CALL setStatus(id, 0)
EXPECT db.hset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
setError_UnitIdAndNewError_UnitErrorSuccessfullyUpdateToDB()
[source]
----
CALL setError(id, 0)
EXPECT db.hset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
setSpeed_UnitIdAndNewSpeed_UnitSpeedSuccessfullyUpdateToDB()
[source]
----
CALL setSpeed(id, 0)
EXPECT db.hset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
testSetPoiList()
[source]
----
SET poiList TO ['(0,0)', '(1,1)']
CALL setPoilist(id, poiList)
EXPECT db.rpush() TO HAVE BEEN CALLED 2 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

===== Persistence - UserRepositoryRedis
====== BEFORE-EACH
[source]
----
SET db TO _mock_
SET test TO new UserRepositoryRedis(db)
SET user TO 'userTest'
SET password TO 'userPassword'
SET admin TO true
----

====== TU
newUser_NewUserToRegister_UserSuccessfullyAddedToDB()
[source]
----
CALL newUser(user, password, admin)
EXPECT db.sadd() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.hmset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
delUser_UserNameToDelete_UserSuccessfullyDeletedToDB()
[source]
----
CALL delUser(id)
EXPECT db.srem() TO HAVE BEEN CALLED 1 TIMES
EXPEXT db.del() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getPassword_UserNameToGetPassword_ReturnPasswordCorrectlyFromDB()
[source]
----
EXPECT test.getPassword() = 'userPassword'
EXPECT db.hget() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
isAdmin_UserName_ReturnTrue()
[source]
----
EXPECT test.isAdmin() = true
EXPECT db.hget() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getUsers_requestToGetUsers_UsersCorrectlyReturned()
[source]
----
CALL getUsers()
EXPECT db.smembers() TO HAVE BEEN CALLED 1 TIMES
----