===== Persistence - MapRepositoryRedis
====== BEFORE-EACH
[source]
----
SET db TO _mock_
SET test TO new MapRepositoryRedis(db)
SET cell TO new Cell((0,0),false,false,RIGHT,false)
----

====== TU
getLength_requestToGetLength_LengthCorrectlyReturned()
[source]
----
CALL getLength()
EXPECT length = '5'
EXPECT db.get() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getHeight_requestToGetHeight_HeightCorrectlyReturned()
[source]
----
CALL getHeight()
EXPECT height = '5'
EXPECT db.get() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getCell_LengthHeight_CellCorrectlyReturned()
[source]
----
CALL getCell(0,0)
EXPECT cell.isLocked = 'false'
EXPECT cell.isBase = 'false'
EXPECT cell.isPoi = 'false'
EXPECT cell.getDirection = 'RIGHT'
EXPECT db.hget() TO HAVE BEEN CALLED 4 TIMES
----

====== TU
setCells_LengthHeightCellList_DeleteExistingCellsAndSetNewCellListToDB()
[source]
----
SET cellList TO new List<Cell> with 4 new Cells
CALL setCells(cellList, 2, 2)
EXPECT db.get() TO HAVE BEEN CALLED 36 TIMES
EXPECT db.del() TO HAVE BEEN CALLED 25 TIMES
EXPECT db.set() TO HAVE BEEN CALLED 2 TIMES
EXPECT db.hmset() TO HAVE BEEN CALLED 4 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getCells_requestToGetCellList_CellListCorrectlyReturned()
[source]
----
CALL getCells()
EXPECT db.get() TO HAVE BEEN CALLED 36 TIMES
EXPECT db.hget() TO HAVE BEEN CALLED 100 TIMES
----

===== Persistence - ObstacleRepositoryRedis
====== BEFORE-EACH
[source]
----
SET db TO _mock_
SET test TO new ObstacleRepositoryRedis(db)
SET id TO 'obs:1'
SET position TO new Position(0,0)
----

====== TU
getObstaclesList_requestToGetObstaclesList_ObstaclesListCorrectlyReturned()
[source]
----
SET obstacleList TO new List<Position> with 3 new Cells
CALL getObstacleList()
EXPECT obstacleList[0] = (0:1)
EXPECT obstacleList[1] = (2:3)
EXPECT obstacleList[2] = (4:5)
EXPECT db.lindex() TO HAVE BEEN CALLED 3 TIMES
----

====== TU
setObstacle_ObstaclePosition_ObstacleSuccessfullyAddedToDB()
[source]
----
CALL setObstacle(position)
EXPECT db.rpush() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
delObstacle_ObstaclePosition_ObstacleSuccessfullyDeletedToDB()
[source]
----
CALL delObstacle(position)
EXPECT db.lrem() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
checkObstacle_ObstaclePosition_ReturnTrueOrFalse()
[source]
----
CALL checkObstacle(position)
EXPECT test.checkObstacle() = 'true'
CALL checkObstacle('(1,1)')
EXPECT test.checkObstacle() = 'false'
EXPECT db.lpos() TO HAVE BEEN CALLED 2 TIMES
----

===== Persistence - UnitRepositoryRedis
====== BEFORE-EACH
[source]
----
SET db TO _mock_
SET test TO new UnitRepositoryRedis(db)
SET id TO 'Unit:1'
SET name TO 'Unità'
SET position TO new Position(0,0)
----

====== TU
newUnit_NewUnitToRegister_UnitSuccessfullyAddedToDB()
[source]
----
CALL newUnit(id, name, position)
EXPECT db.sadd() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.hmset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
delUnit_UnitIdToDelete_UnitSuccessfullyDeletedToDB()
[source]
----
CALL delUnit(id)
EXPECT db.del() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.srem() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getUnits_requestToGetUnits_UnitsCorrectlyReturned()
[source]
----
CALL getUnits()
EXPECT db.smembers() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getName_UnitIdToGetName_ReturnNameCorrectlyFromDB()
[source]
----
EXPECT test.getName(id) = 'Unità'
EXPECT db.hget() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
isUnit_UnitId_ReturnTrue()
[source]
----
EXPECT test.isUnit(id) = true
EXPECT db.hget() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getBase_UnitIdToGetBase_ReturnBaseCorrectlyFromDB()
[source]
----
SET base_x TO '5'
SET base_y TO '5'
EXPECT test.getBase() = '(5,5)'
EXPECT db.hget() TO HAVE BEEN CALLED 2 TIMES
----

====== TU
getPosition_UnitIdToGetPosition_ReturnPositionCorrectlyFromDB()
[source]
----
SET position_x TO '5'
SET position_y TO '5'
EXPECT test.getPosition(id) = '(5,5)'
EXPECT db.hget() TO HAVE BEEN CALLED 2 TIMES
----

====== TU
getPoiList_UnitId_UnitPoiListCorrectlyReturned()
[source]
----
SET poi:id TO ['(0,1)', '(2,3)', '(4,5)']
EXPECT getPoiList(id) = ['(0,1)', '(2,3)', '(4,5)']
EXPECT db.lindex() TO HAVE BEEN CALLED 3 TIMES
----

====== TU
setPosition_UnitIdAndNewPosition_UnitPositionSuccessfullyUpdateToDB()
[source]
----
CALL setPosition(id, position)
EXPECT db.hmset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
setStatus_UnitIdAndNewStatus_UnitStatusSuccessfullyUpdateToDB()
[source]
----
CALL setStatus(id, 0)
EXPECT db.hset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
setError_UnitIdAndNewError_UnitErrorSuccessfullyUpdateToDB()
[source]
----
CALL setError(id, 0)
EXPECT db.hset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
setSpeed_UnitIdAndNewSpeed_UnitSpeedSuccessfullyUpdateToDB()
[source]
----
CALL setSpeed(id, 0)
EXPECT db.hset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
testSetPoiList()
[source]
----
SET poiList TO ['(0,0)', '(1,1)']
CALL setPoilist(id, poiList)
EXPECT db.rpush() TO HAVE BEEN CALLED 2 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

===== Persistence - UserRepositoryRedis
====== BEFORE-EACH
[source]
----
SET db TO _mock_
SET test TO new UserRepositoryRedis(db)
SET user TO 'userTest'
SET password TO 'userPassword'
SET admin TO true
----

====== TU
newUser_NewUserToRegister_UserSuccessfullyAddedToDB()
[source]
----
CALL newUser(user, password, admin)
EXPECT db.sadd() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.hmset() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
delUser_UserNameToDelete_UserSuccessfullyDeletedToDB()
[source]
----
CALL delUser(id)
EXPECT db.srem() TO HAVE BEEN CALLED 1 TIMES
EXPEXT db.del() TO HAVE BEEN CALLED 1 TIMES
EXPECT db.bgsave() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getPassword_UserNameToGetPassword_ReturnPasswordCorrectlyFromDB()
[source]
----
EXPECT test.getPassword() = 'userPassword'
EXPECT db.hget() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
isAdmin_UserName_ReturnTrue()
[source]
----
EXPECT test.isAdmin() = true
EXPECT db.hget() TO HAVE BEEN CALLED 1 TIMES
----

====== TU
getUsers_requestToGetUsers_UsersCorrectlyReturned()
[source]
----
CALL getUsers()
EXPECT db.smembers() TO HAVE BEEN CALLED 1 TIMES
----