===== WebSocketService - TU[76-98]
====== BEFORE-EACH
[source]
----
SET map TO _stub_
SET subject TO _stub_
SET socket TO _stub_
SET service TO new WebSocketService(map, map, map, subject, subject, subject, socket)
----

====== TU76
It should be created.
[source]
----
EXPECT service TO EXIST
EXPECT socket.subscribe() TO HAVE BEEN CALLED 1 TIMES
----

====== TU77
It should receive a "KeepAliveFromServer" message and do nothing.
[source]
----
SET msg TO new KeepaliveFromServer
CALL service.onMessage(msg)

EXPECT service.getAuthStatus() = AuthStatus.NO_AUTH
EXPECT map.get() TO HAVE BEEN CALLED 0 TIMES
EXPECT map.Set() TO HAVE BEEN CALLED 0 TIMES
EXPECT socket.next() TO HAVE BEEN CALLED 0 TIMES
EXPECT subject.next() TO HAVE BEEN CALLED 0 TIMES
----

====== TU78
It should receive a "AuthFromServer" message and change authStatus to "ADMIN".
[source]
----
SET msg TO new AuthFromServer(session = 'ADMIN')
CALL service.onMessage(msg)

EXPECT service TO EXIST
EXPECT service.getAuthStatus() = AuthStatus.ADMIN
----

====== TU79
It should receive a "UsersFromServer" message and update internal User data structure.
[source]
----
SET listOfUsers TO new User[n]
SET msg TO new UsersFromServer(users = listOfUsers)
CALL service.onMessage(msg)

EXPECT map.clear() TO HAVE BEEN CALLED 1 TIMES
EXPECT map.set() TO HAVE BEEN CALLED n TIMES WITH listOfUsers[0..n]
EXPECT subject.next() TO HAVE BEEN CALLED 1 TIMES WITH listOfUsers;
----

====== TU80
It should receive a "UnitsFromServer" message and update internal Unit data structure.
[source]
----
SET listOfUnits TO new Unit[n]
SET msg TO new AuthFromServer(units = listOfUnits)
CALL service.onMessage(msg)

EXPECT map.clear() TO HAVE BEEN CALLED 1 TIMES
EXPECT map.set() TO HAVE BEEN CALLED n TIMES WITH listOfUnits[0..n]
EXPECT subject.next() TO HAVE BEEN CALLED 1 TIMES WITH listOfUnits;
----

====== TU81
It should receive a "MapFromServer" message and update internal Cell data structure.
[source]
----
SET listOfCells TO new Cell[n]
SET msg TO new MapFromServer(cells = listOfCells)
CALL service.onMessage(msg)

EXPECT map.clear() TO HAVE BEEN CALLED 1 TIMES
EXPECT map.set() TO HAVE BEEN CALLED n TIMES WITH listOfUnits[0..n]
EXPECT subject.next() TO HAVE BEEN CALLED 1 TIMES WITH new listOfUnits;
EXPECT service.getMapHeight() = msg.height;
EXPECT service.getMapLength() = msg.length;
----

====== TU82
It should receive a "UnitStatusFromServer" message with a known id, status "ERROR" and change internal data.
[source]
----
SET unit TO new Unit(id = 'unit1')
CALL map.set('unit1', unit)
SET msg TO new UnitStatusFromServer(id = 'unit1', status = 'ERROR')
CALL service.onMessage(msg)

EXPECT map.has() TO HAVE BEEN CALLED 1 TIMES
EXPECT map.get() TO HAVE BEEN CALLED 1 TIMES WITH 'unit1'
EXPECT unit.getStatus() = UnitStatus.ERROR
EXPECT subject.next() TO HAVE BEEN CALLED 1 TIMES WITH unit
EXPECT STDOUT TO BE EMPTY
----

====== TU83
It should receive a "UnitPoiFromServer" message with a known id, list of POI and change internal data.
[source]
----
SET unit TO new Unit(id = 'unit1')
CALL map.set('unit1', unit)
SET listOfPoi TO new Position[n]
SET msg TO new UnitPoiFromServer(id = 'unit1', poi = listOfPoi)
CALL service.onMessage(msg)

EXPECT map.has() TO HAVE BEEN CALLED 1 TIMES
EXPECT map.get() TO HAVE BEEN CALLED 1 TIMES WITH 'unit1'
EXPECT unit.getPoiList() = listOfPoi
EXPECT subject.next() TO HAVE BEEN CALLED 1 TIMES WITH unit
EXPECT STDOUT TO BE EMPTY
----

====== TU84
It should receive a "UnitSpeedFromServer" message with a known id, a new speed value and change internal data.
[source]
----
SET unit TO new Unit(id = 'unit1')
CALL map.set('unit1', unit)
SET msg TO new UnitPoiFromServer(id = 'unit1', speed = speed)
CALL service.onMessage(msg)

EXPECT map.has() TO HAVE BEEN CALLED 1 TIMES
EXPECT map.get() TO HAVE BEEN CALLED 1 TIMES WITH 'unit1'
EXPECT unit.getSpeed() = speed
EXPECT subject.next() TO HAVE BEEN CALLED 1 TIMES WITH unit
EXPECT STDOUT TO BE EMPTY
----

====== TU85
It should receive a "UnitErrorFromServer" with a known id, a new error code and change internal data.
[source]
----
SET unit TO new Unit(id = 'unit1')
CALL map.set('unit1', unit)
SET msg TO new UnitPoiFromServer(id = 'unit1', position)
CALL service.onMessage(msg)

EXPECT map.has() TO HAVE BEEN CALLED 1 TIMES
EXPECT map.get() TO HAVE BEEN CALLED 1 TIMES WITH 'unit1'
EXPECT unit.getPosition() = position
EXPECT subject.next() TO HAVE BEEN CALLED 1 TIMES WITH unit
EXPECT STDOUT TO BE EMPTY
----

====== TU86
It should receive a "UnitPosFromServer" message with a known id, a new current position and change internal data.
[source]
----
SET unit TO new Unit(id = 'unit1', position = oldPosition)
CALL map.set('unit1', unit)

SET fakeCellInOldPosition TO new Cell(
position = unit.getPosition(), unit = unit.getId())
CALL map.set(unit.getPosition(), fakeCellInOldPosition);

SET fakeCellInNewPosition TO new Cell(
position = newPosition, unit = '')
CALL map.set(newPosition, fakeCellInNewPosition);

SET msg TO new UnitPoiFromServer(id = 'unit1', position = newPosition)
CALL service.onMessage(msg)

EXPECT map.has() TO HAVE BEEN CALLED 1 TIMES
EXPECT map.get() TO HAVE BEEN CALLED 3 TIMES
EXPECT map.get() TO HAVE BEEN CALLED WITH 'unit1'
EXPECT map.get() TO HAVE BEEN CALLED WITH oldPosition
EXPECT map.get() TO HAVE BEEN CALLED WITH newPosition
EXPECT unit.getPosition() = newPosition
EXPECT fakeCellInOldPosition.getUnit() = ''
EXPECT fakeCellInNewPosition.getUnit() = 'unit1'
EXPECT subject.next() TO HAVE BEEN CALLED 2 TIMES
EXPECT subject.next() TO HAVE BEEN CALLED WITH [fakeCellInOldPosition, fakeCellInNewPosition]
EXPECT subject.next() TO HAVE BEEN CALLED unit
EXPECT STDOUT TO BE EMPTY
----

====== TU87
It should receive a "Unit*FromServer" with unknown id, not change internal data and print error message.
[source]
----
FOREACH MsgType IN [
      UnitStatusFromServer,
      UnitPoiFromServer,
      UnitSpeedFromServer,
      UnitErrorFromServer,
      UnitPosFromServer,
] DO
    SET msg TO new MsgType(id = 'unitX')
    CALL service.onMessage(msg)

    EXPECT map.has() TO HAVE BEEN CALLED 1 TIMES
    EXPECT map.get() TO HAVE BEEN CALLED 0 TIMES
    EXPECT subject.next() TO HAVE BEEN CALLED 0 TIMES
    EXPECT STDOUT TO DISPLAY ERROR
----

====== TU88
It should send a login request through socket by giving an obj with username and password.
[source]
----
CALL service.login(username, password)

EXPECT socket.next() TO HAVE BEEN CALLED 1 TIMES WITH (JSON) new LoginToServer(username, password)
----

====== TU89
It should send a logout request through socket by giving an obj with username.
[source]
----
CALL service.logout(username)

EXPECT socket.next() TO HAVE BEEN CALLED 1 TIMES WITH (JSON) new LogoutToServer(username)
----

====== TU90
It should send two new user request through socket by giving each time an obj with user data
[source]
----
CALL service.addUser(
    username = username1,
    password = password1,
    admin = false)
CALL service.addUser(
    username = username2,
    password = password2,
    admin = true)

EXPECT socket.next() TO HAVE BEEN CALLED 2 TIMES
EXPECT socket.next() TO HAVE BEEN CALLED WITH (JSON) new UserToServer(username1, password1, false)
EXPECT socket.next() TO HAVE BEEN CALLED WITH (JSON) new UserToServer(username2, password2, true)
----

====== TU91
It should send a delete user request through socket by giving an obj with username.
[source]
----
CALL service.deleteUser(username)

EXPECT socket.next() TO HAVE BEEN CALLED 1 TIMES WITH (JSON) new DeleteUserToServer(username)
----

====== TU92
It should send an add unit request through socket by giving an obj with unit data.
[source]
----
CALL service.addUnit(id, name, position)

EXPECT socket.next() TO HAVE BEEN CALLED 1 TIMES WITH (JSON) new UnitToServer(id, name, position)
----

====== TU93
It should send a delete unit request through socket by giving an obj with unit data.
[source]
----
CALL service.deleteUnit(id)

EXPECT socket.next() TO HAVE BEEN CALLED 1 TIMES WITH (JSON) new DeleteUnitToServer(id)
----

====== TU94
It should send a start unit request through socket by giving an obj with id and poi list.
[source]
----
SET listOfPoi TO new Position[n]
CALL service.start(id, listOfPoi)

EXPECT socket.next() TO HAVE BEEN CALLED 1 TIMES WITH (JSON) new UnitStartToServer(id, listOfPoi)
----

====== TU95
It should send a stop unit request through socket by giving an obj with unit id and stop command.
[source]
----
CALL service.stop(id)

EXPECT socket.next() TO HAVE BEEN CALLED 1 TIMES WITH (JSON) new UnitStopToServer(id, UnitStopCommand.STOP)
----

====== TU96
It should send a shutdown unit request through socket by giving an obj with unit id and shutdown command.
[source]
----
CALL service.shutdown(id)

EXPECT socket.next() TO HAVE BEEN CALLED 1 TIMES WITH (JSON) new UnitStopToServer(id, UnitStopCommand.SHUTDOWN)
----

====== TU97
It should send a goback unit request through socket by giving an obj with unit id and goback command.
[source]
----
CALL service.goback(id)

EXPECT socket.next() TO HAVE BEEN CALLED 1 TIMES WITH (JSON) new UnitStopToServer(id, UnitStopCommand.BASE)
----

====== TU98
It should send a new map request through socket by giving an obj with map string extracted from file.
[source]
----
CALL service.newMap(map)

EXPECT socket.next() TO HAVE BEEN CALLED 1 TIMES WITH (JSON) new MapToServer(map)
----
