name: Continuos Integration for LaTeX

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v2

    - name: Latex compiler
      uses: Jatus93/Latex-multicompiler@master
      with:
        path_to_list: .github/files_to_compile
        artifact: true

    - name: Spell Check
      uses: Jatus93/spellCheck@master
      with:
        directory: ./Documents
        languages: "en_GB;en_US;italiano"

    - name: Gulpease
      uses: achimett/GulpeaseTex@master
      with:
        files-to-evaluate: .github/files_to_compile
        directory: Documents/Gulpease

    - name: Upload artifact
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: Documents
        path: ./Documents
